reinfolib:
  target: default
  outputs:
    default:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: reinfolib
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
      attach:
        - path: "md:reinfolib"
          alias: reinfolib
          is_ducklake: true
    local:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: reinfolib
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
      attach:
        - path: "md:dev_reinfolib"
          alias: reinfolib
          is_ducklake: true
